"""profile fields + pgcrypto

Revision ID: 1baf1247a1bf
Revises: 28537b12be97
Create Date: 2026-05-27 16:43:03.119130

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1baf1247a1bf'
down_revision: str | None = '28537b12be97'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishment_profiles', sa.Column('neighborhood', sa.String(length=100), nullable=True))
    op.add_column('establishment_profiles', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('establishment_profiles', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('establishment_profiles', sa.Column('cep', sa.String(length=8), nullable=True))
    op.add_column('establishment_profiles', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('establishment_profiles', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('establishment_profiles', sa.Column('cnpj_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('freelancer_profiles', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('freelancer_profiles', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('freelancer_profiles', sa.Column('cpf_encrypted', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freelancer_profiles', 'cpf_encrypted')
    op.drop_column('freelancer_profiles', 'avatar_url')
    op.drop_column('freelancer_profiles', 'phone')
    op.drop_column('establishment_profiles', 'cnpj_encrypted')
    op.drop_column('establishment_profiles', 'avatar_url')
    op.drop_column('establishment_profiles', 'phone')
    op.drop_column('establishment_profiles', 'cep')
    op.drop_column('establishment_profiles', 'state')
    op.drop_column('establishment_profiles', 'city')
    op.drop_column('establishment_profiles', 'neighborhood')
    # ### end Alembic commands ###
